config/routes.rb
SampleApp::Application.routes.draw do
  resources :users
  resources :sessions, only: [:new, :create, :destroy]
  resources :posts, only: [:create, :destroy]

  root :to => 'pages#home'
  match '/contact', :to => 'pages#contact'
  match '/about', :to => 'pages#about'
  match '/help', :to => 'pages#help'
  match '/signup', :to => 'users#new'
  match '/signin', :to => 'sessions#new'
  match '/signout', :to => 'sessions#destroy'

end

app/models/post.rb
class Post < ActiveRecord::Base
  attr_accessible :content
  belongs_to :user

  validates :content, presence: true, length: { maximum: 63206 }
  validates :user_id, presence: true 

  default_scope order: 'posts.created_at DESC'

  def all_posts
    Post.where("user_id > 0")
  end
end

app/models/user.rb
# == Schema Information
#
# Table name: users
#
#  id              :integer         not null, primary key
#  name            :string(255)
#  email           :string(255)
#  created_at      :datetime        not null
#  updated_at      :datetime        not null
#  password_digest :string(255)
#  admin           :boolean         default(FALSE)
#

class User < ActiveRecord::Base
  attr_accessible :name, :email, :password, :password_confirmation
  has_secure_password
  has_many :posts, dependent: :destroy

  email_regex = /\A[\w+\-.]+@[a-z\d\-.]+\.[a-z]+\z/i

  validates :name, :presence => true,
                   :length   => { :maximum => 50 }
  validates :email, :presence   => true,
                    :format     => { :with => email_regex },
                    :uniqueness => { :case_sensitive => false }

  validates :password, presence: true

  def feed
    # Post.where("user_id != ?", id)
    Post.where("user_id > 0")
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery
  include SessionsHelper
end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
  def home
    @title = "Home"
    if signed_in?
      @post = current_user.posts.build if signed_in?
      @feed_items = current_user.feed.paginate(page: params[:page])
    else
      @feed_items = Post.where("user_id > 0").paginate(page: params[:page])
    end
  end

  def contact
    @title = "Contact"
  end

  def about
    @title = "About"
  end

  def help
    @title = "Help"
  end
end

app/controllers/posts_controller.rb
class PostsController < ApplicationController
  before_filter :signed_in_user, only: [:create, :destroy]
  before_filter :correct_user, only: :destroy

  def create
    @post = current_user.posts.build(params[:post])
    if @post.save
      flash[:success] = "Post created!"
      redirect_to root_path
    else
      @feed_items = []
      render 'pages/home'
    end
  end

  def destroy
    @post.destroy
    redirect_back_or root_path
  end

  private

  def correct_user
    @post = current_user.posts.find_by_id(params[:id])
    redirect_to root_path if @post.nil?
  end
end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController

  def new
    @title = "Sign in"
  end

  def create
    user = User.find_by_email(params[:email])
    if user && user.authenticate(params[:password])
      # sign in and redirect to user's show page
      sign_in user
      redirect_back_or user
    else
      # create an errer and re-render login form
      flash.now[:error] = 'Invalid email/password combination.'
      @title = "Sign in"
      render 'new'
    end
  end

  def destroy
    sign_out
    redirect_to root_path
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_filter :signed_in_user, only: [:edit, :update, :index]
  before_filter :correct_user, only: [:edit, :update]
  before_filter :admin_user, only: :destroy

  def index
    @title = "All users"
    @users = User.paginate(page: params[:page])
  end

  def show
    @user = User.find(params[:id])
    @posts = @user.posts.paginate(page: params[:page])
    @title = @user.name
  end

  def new
    @title = "Sign up"
    @user = User.new
  end

  def create
    @user = User.new(params[:user])
    if @user.save
      sign_in @user
      flash[:success] = "New user successfully registered."
      redirect_to @user
    else
      render 'new'
    end
  end

  def edit
    @title = "Edit user"
  end

  def update
    if @user.update_attributes(params[:user])
      flash[:success] = "Profile updated"
      redirect_to @user
    else
      render 'edit'
    end
  end

  def destroy
    User.find(params[:id]).destroy
    flash[:success] = "User deleted."
    redirect_to users_path
  end

  private

    def correct_user
      @user = User.find(params[:id])
      redirect_to(root_path) unless current_user?(@user)
    end

    def admin_user
      redirect_to(root_path) unless current_user.admin?
    end
end

app/helpers/application_helper.rb
module ApplicationHelper

  # Return a title on a per-page basis.
  def page_title
    base_title = "iMicIt"
    if @title.nil?
      base_title
    else
      "#{base_title} | #{@title}"
    end
  end

  def logo
    image_tag("logo.png", :alt => "iMicIt", :class => "round")
  end
end

app/helpers/pages_helper.rb
module PagesHelper
end

app/helpers/sessions_helper.rb
module SessionsHelper

  def sign_in(user)
    session[:user_id] = user.id
    current_user = user
  end

  def signed_in?
    !current_user.nil?
  end

  def current_user=(user)
    @current_user = user
  end

  def current_user
    @current_user ||= User.find(session[:user_id]) if session[:user_id]
  end

  def current_user?(user)
    user == current_user
  end

  def signed_in_user
    unless signed_in?
      store_location
      redirect_to signin_path, notice: "Please sign in."
    end
  end

  def sign_out
    session[:user_id] = nil
  end

  def redirect_back_or(default)
    redirect_to(session[:redirect_to] || default)
    clear_return_to
  end

  def store_location
    session[:redirect_to] = request.fullpath
  end

  private
  
    def clear_return_to
      session.delete(:return_to)
    end
end

app/helpers/users_helper.rb
module UsersHelper
  def gravatar_for(user, options = { :size => 50 })
    gravatar_image_tag(user.email.downcase, :alt => user.name, 
                                            :class => 'gravatar',
                                            :gravatar => options)
  end
end

app/views/layouts/_footer.html.haml
%footer
  %nav
    %ul
      %li= link_to "About", about_path
      %li= link_to "Contact", contact_path
      %li
        %a{:href => "http://machindoapps.com"} Machindo Apps

app/views/layouts/_header.html.haml
%header.navbar.navbar-fixed-top
  .navbar-inner
    .container
      = link_to logo, root_path, id: "logo"
      %nav
        %ul.nav.pull-right
          %li= link_to "Home", root_path
          %li= link_to "Users", users_path
          - if signed_in?
            %li= link_to "Profile", current_user
            %li= link_to "Settings", edit_user_path(current_user)
          %li= link_to "Help", help_path
          - if signed_in?
            %li= link_to "Sign out", signout_path, method: :delete
          - else
            %li= link_to "Sign in", signin_path

app/views/layouts/_nav_left.html.haml
.well.sidebar-nav.left
  %ul.nav.nav-list
    %li.nav-header
    %li.active
      %a{:href => "#"} View All
    %li
      %a{:href => "#"} Astor
    %li
      %a{:href => "#"} Brewery District
    %li
      %a{:href => "#"} Cornole
    %li
      %a{:href => "#"} Brifterville
    %li
      %a{:href => "#"} Far Wesst
    %li
      %a{:href => "#"} Ghoulville
    %li
      %a{:href => "#"} Motown
    %li
      %a{:href => "#"} Showtown
    %li
      %a{:href => "#"} Zotown

app/views/layouts/_nav_right.html.haml
.well
  Right sidebar content placeholder

app/views/layouts/_shim.html.haml
/[if lt IE 9]
  <script src="http://html5shim.googlecode.com/svn/trunk/html5.js"></script>

app/views/layouts/_toolbar.html.haml
.btn-toolbar.center{"style" => "margin-top: 0px;"}
  .btn-group
    %a.btn.dropdown-toggle{"data-toggle" => "dropdown"}
      Feed
      %span.caret
    %ul.dropdown-menu
      %li
        %a{:href => "#"} Add New
  .btn-group
    %a.btn.dropdown-toggle{"data-toggle" => "dropdown"}
      Shots
      %span.caret
    %ul.dropdown-menu
      %li
        %a{:href => "#"} Add New
  .btn-group
    %a.btn.dropdown-toggle{"data-toggle" => "dropdown"}
      Events
      %span.caret
    %ul.dropdown-menu
      %li
        %a{:href => "#"} Add New

app/views/layouts/application.html.haml
!!!
%html
  %head
    %title= page_title
    = stylesheet_link_tag "application", media: "all"
    = javascript_include_tag "application", "bootstrap-dropdown"
    = csrf_meta_tags
    = render 'layouts/shim'
  %body
    = render 'layouts/header'
    .container
      %section.round
        - flash.each do |key, value|
          = content_tag(:div, value, class: "flash #{key}")
        = yield
      = render 'layouts/footer'
      = debug(params) if Rails.env.development?

app/views/pages/about.html.haml
%h1 About Page
%p
  This is the iMicIt About Page.

app/views/pages/contact.html.haml
%h1 Contact Page
%p
  Contact us here.

app/views/pages/help.html.haml
%h1 Help Page
%p 
  This is the help page. 

app/views/pages/home.html.haml
!!!
//.well
.container-fluid
  - if signed_in?
    .row-fluid
      = render 'layouts/toolbar'
  .row-fluid
    .span3
      = render 'layouts/nav_left'
    .span6
      .well
        = render 'shared/feed'
    .span3
      = render 'layouts/nav_right'
      - if signed_in?
        = render 'shared/post_form'

app/views/posts/_post.html.haml
%li
  %span.content= post.content
  %span.timestamp
    Posted #{time_ago_in_words(post.created_at)} ago

app/views/shared/_error_messages.html.haml
- if object.errors.any?
  #error_explanation
    .alert.alert-error
      The form contains #{pluralize(object.errors.count, "error")}
    %ul
      - object.errors.full_messages.each do |msg|
        %li
          #{msg}

app/views/shared/_feed.html.haml
- if @feed_items.any?
  %ol.posts
    = render partial: 'shared/feed_item', collection: @feed_items
  = will_paginate @feed_items

app/views/shared/_feed_item.html.haml
%li{:id => feed_item.id}
  = link_to gravatar_for(feed_item.user), feed_item.user
  %span.user
    = link_to feed_item.user.name, feed_item.user
  %span.content= feed_item.content
  %span.timestamp
    #{time_ago_in_words(feed_item.created_at)} ago at #{feed_item.created_at}.
  - if current_user
    - if current_user?(feed_item.user) || current_user.admin?
      = link_to "delete", feed_item, method: :delete,
        confirm: "Are you sure you want to delete this post?",
        title: feed_item.content

app/views/shared/_post_form.html.haml
= form_for(@post) do |f|
  = render 'shared/error_messages', object: f.object
  .field
    = f.text_area :content, placeholder: "Post text..."
  = f.submit "Post", class: "btn btn-primary"

app/views/shared/_user_info.html.haml
%a{:href => user_path(@user)}
  = gravatar_for @user, size: 52
%h3
  = @user.name
%span
  = pluralize(@user.posts.count, "post")

app/views/users/_user.html.haml
%li
  = gravatar_for user, size: 50
  = link_to user.name, user
  - if current_user.admin? && !current_user?(user)
    | 
    = link_to "delete", user, method: :delete, confirm: "Really delete this user?"

app/views/users/edit.html.haml
- provide :title, "Edit user"
%h1 Edit user
= form_for(@user) do |f|
  = render 'shared/error_messages', object: f.object
  .field
    = f.label :name
    %br/
    = f.text_field :name
  .field
    = f.label :email
    %br/
    = f.text_field :email
  .field
    = f.label :password
    %br/
    = f.password_field :password
  .field
    = f.label :password_confirmation, "Confirmation"
    %br/
    = f.password_field :password_confirmation
  .actions
    = f.submit "Update"
%div
  = gravatar_for(@user)
  %a{ :href => "http://gravatar.com/emails" } change

app/views/users/index.html.haml
%h1 All users

= will_paginate

%ul.users
  = render @users

= will_paginate

app/views/users/new.html.haml
= provide(:title, 'Sign up')
%h1 Sign up
= form_for(@user) do |f|
  = render 'shared/error_messages', object: f.object
  .field
    = f.label :name
    %br/
    = f.text_field :name
  .field
    = f.label :email
    %br/
    = f.text_field :email
  .field
    = f.label :password
    %br/
    = f.password_field :password
  .field
    = f.label :password_confirmation, "Confirm Password"
    %br/
    = f.password_field :password_confirmation
  .actions
    = f.submit "Sign Up"

app/views/users/show.html.haml
- provide :title, @user.name
.container-fluid
  .row-fluid
    = render 'layouts/toolbar'
  .row-fluid
    .span3
      = render 'layouts/nav_left'
    .span6
      .well
        - if @user.posts.any?
          %h3
            Posts (#{@user.posts.count})
          %ol.posts
            = render @posts
          = will_paginate @posts
    .span3
      = render 'layouts/nav_right'
      = render 'shared/user_info'